name: Update Date in README

on:
  schedule:
    # Runs every day at 12:00 AM Nepal Time (18:15 UTC)
    - cron: "15 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Kathmandu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "khushichaudhary18"
          git config --global user.email "khushichaudhary2063@gmail.com"

      - name: Make script executable
        run: chmod +x script.sh

      - name: Update README date
        run: ./script.sh

      - name: Commit and Push changes
        run: |
          git add README.md

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: update README date"
          git push
